id: e2d31c77a462429394ade9e0315cc968
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_218-Purification_of_Karmic_Obscurations-v1
  language: bo
  author: ''
  volume: {}
